google_search: true ## Use Google search, true/false.
baidu_search: true ## Use Baidu search, true/false.
baidu_analytics: 3833b8b9011cb597dba0de1d7c75d966 ## Your Baidu Analytics tracking id, e.g. 8006843039519956000
show_category_count: true ## If you want to show the count of categories in the sidebar widget please set the value to true.
wordcount: true ## If you want to display the word counter and the reading time expected to spend of each post please set the value to true, and you must have hexo-wordcount installed.
widgets_on_small_screens: true ## Set to true to enable widgets on small screens.
post_copyright:
  enable: true ## If you want to display the copyright info after each post, please set the value to true and fill the following items on your need.
  author: 飞尘 ## Your author name, e.g. tufu9441
  copyright_text: 本站所有文章除特别声明外，均可转载，转载请注明出处！ ## Your copyright text, e.g. The author owns the copyright, please indicate the source reproduced.

menu:
  - page: home
    directory: .
    icon: icon-home
  - page: archive
    directory: archives/
    icon: icon-archive
  - page: about
    directory: about/
    icon: icon-user

widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts and links.
  - search
  - category
  - tag
  # - recent_posts

version: "1.2"