gitalk:
  enable: true ## If you want to use Gitalk comment system please set the value to true.
  owner: felix-fly ## Your GitHub ID, e.g. username
  repo: felix-fly.github.io ## The repository to store your comments, make sure you're the repo's owner, e.g. gitalk.github.io
  client_id: be0f473e7c298869acd2 ## GitHub client ID, e.g. 75752dafe7907a897619
  client_secret: 9a27862b9f3164f89303a63725739ee1fb49ba73 ## GitHub client secret, e.g. ec2fb9054972c891289640354993b662f4cccc50
  admin: ['felix-fly'] ## Github repo owner and collaborators, only these guys can initialize github issues.

google_search: true ## Use Google search, true/false.
baidu_search: true ## Use Baidu search, true/false.
google_analytics: ## Your Google Analytics tracking id, e.g. UA-42425684-2
baidu_analytics: 3833b8b9011cb597dba0de1d7c75d966 ## Your Baidu Analytics tracking id, e.g. 8006843039519956000
show_category_count: true ## If you want to show the count of categories in the sidebar widget please set the value to true.
shareto: true ## If you want to use the share button please set the value to true, and you must have hexo-helper-qrcode installed.
busuanzi: false ## If you want to use Busuanzi page views please set the value to true.
wordcount: true ## If you want to display the word counter and the reading time expected to spend of each post please set the value to true, and you must have hexo-wordcount installed.
widgets_on_small_screens: true ## Set to true to enable widgets on small screens.
post_copyright:
  enable: true ## If you want to display the copyright info after each post, please set the value to true and fill the following items on your need.
  author: 飞尘 ## Your author name, e.g. tufu9441
  copyright_text: 本站所有文章除特别声明外，均可转载，转载请注明出处！ ## Your copyright text, e.g. The author owns the copyright, please indicate the source reproduced.

menu:
  - page: home
    directory: .
    icon: icon-home
  - page: archive
    directory: archives/
    icon: icon-archive
  - page: about
    directory: about/
    icon: icon-user

widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts and links.
  - search
  - category
  - tag
  # - recent_posts
  # - links

links:
  - title: 来UI
    url: https://www.laiui.com/

# Static files
js: js
css: css
